Feature/mobal win
Y0less/The-Watch-Spot-Team-project pull request #10
Opened 2023-04-22 09:03 UTC by sili41995

add new markup and script

2023-04-22 15:30 UTC, Y0less requested changes
Форма не приймає Імя та прізвище, лише щось одне.  Не приймає цифри в полі для картки. Але цк домашки, Всуодно чекаємо на секцію catalog

![image](https://user-images.githubusercontent.com/125226395/233793194-a33ee63d-e989-447e-b319-3bc5755dc2db.png)

2023-04-22 15:33 UTC, sili41995 commented
у полі для картки є підсказка, що валідний запис картки у форматі хххх-хххх-хххх-хххх. з імям зараз розберуся

2023-04-23 12:26 UTC, Y0less approved these changes
Супер

2023-04-23 12:26 UTC, Y0less commented
Все ОК!

2023-04-23 12:26 UTC, merged