Feature/catalog
Y0less/The-Watch-Spot-Team-project pull request #12
Opened 2023-04-22 16:13 UTC by ValentynaJasochka

Створила секцію catalog зі стилями

2023-04-22 17:01 UTC, Y0less commented
Все виглядає супер!
Є лише один момент, внутрішні в секції верхній і нижній падінги задавай не на контейнер а на секцію.
Решта все бомба. Виправляй і мерджимо!

2023-04-22 17:02 UTC, Y0less requested changes
Все виглядає супер!
Є лише один момент, внутрішні в секції верхній і нижній падінги задавай не на контейнер а на секцію.
Решта все бомба. Виправляй і мерджимо!

2023-04-22 18:40 UTC, ValentynaJasochka commented
Зробила. В desctop тільки padding нижній. а mobile i tablet є

2023-04-22 21:10 UTC, Y0less commented
в десктопній версії в тебе є верхній падінг в секції 80px, фіговий дизайн, але що поробиш

2023-04-23 10:24 UTC, ValentynaJasochka commented
додала padding 80px на section catalog

2023-04-23 11:07 UTC, Y0less approved these changes

2023-04-23 11:08 UTC, merged