feature/header
Y0less/The-Watch-Spot-Team-project pull request #14
Opened 2023-04-23 10:32 UTC by skrinskanastya

header, mobile menu added

2023-04-23 14:33 UTC, sili41995 requested changes
1. у мобільному меню кнопки закриття невидно, але вона є...
2. кнопка відкриття і закриття мають бути одна під однодною, хоч трохи... а зараз вони не повязані.
3. не ті розміри для хедера у мобільному
4. відсутні фіксовані розміри до першого елемента мобільного меню
5. при переході на десктоп мобільне меню не зникає, якщо було відкрито до цього
6. кнопка з телефоном у планшеті не відповідає розмірам... і взагалі, то повинна буди не кнопка, а посилання. та гадаю, що ніхто не причепиться до того, що це кнопка...
7. 

![01](https://user-images.githubusercontent.com/124524007/233845644-91b5c958-0fcf-4ae1-a154-fb913c737cef.jpg)
![02](https://user-images.githubusercontent.com/124524007/233845645-14981890-7ce7-443e-a6c2-5a832ddbff15.jpg)
![03](https://user-images.githubusercontent.com/124524007/233845646-2a7fdb91-808d-4c83-ae30-da8d2b581f42.jpg)
![04](https://user-images.githubusercontent.com/124524007/233845647-d2a897fc-f8f3-462c-88b3-3997235ba9a3.jpg)
![05](https://user-images.githubusercontent.com/124524007/233845649-8c6e08a5-b9f7-4dca-b7ac-12fb9eb84693.jpg)
![06](https://user-images.githubusercontent.com/124524007/233845651-2c4cebaf-75a6-4a10-84a6-0d6bdc5bddf4.jpg)

2023-04-23 15:17 UTC, Y0less commented
![image](https://user-images.githubusercontent.com/125226395/233848168-5dcff648-0ef9-4836-8f58-81533c707c5e.png)
верхній падінг на мобілці має бути 29px

2023-04-23 15:23 UTC, Y0less requested changes
Треба зробити багато виправлень, покищо попрацюй над тим що описано, далі побачим

2023-04-23 15:23 UTC, Y0less commented on src/partials/header.html
> +          <use href="/src/img/icons.svg#cross-big"></use>
неправильний шлях до іконки, має бути href="/img/icons.svg#cross-big"

2023-04-23 15:23 UTC, Y0less commented on src/css/header.css
> +  display: flex;
на кнопці флекса не потрібно, саму кнопку привильно відпозиціонуй абсолютом

2023-04-23 15:23 UTC, Y0less commented on src/css/header.css
> +  height: 24px;
задавай на кнопку розмірів, задай нульові падінги, хай обіжметься по іконці.

2023-04-24 17:42 UTC, sili41995 approved these changes
все чудово

2023-04-25 00:10 UTC, Y0less approved these changes

2023-04-25 00:11 UTC, merged