add images
Y0less/The-Watch-Spot-Team-project pull request #3
Opened 2023-04-21 13:01 UTC by ValentynaJasochka

Додала всі зображення

2023-04-21 15:53 UTC, Y0less requested changes
- в папці "hero" є зайві файли для слайдера, адже слайдер має свої власні папочки
- я думаю що 3х файли нам не обовязково, але якщо маєш бажання то лиши

2023-04-21 15:53 UTC, Y0less commented on src/img/buy-now/buy-now-desktop.jpg
В buy now картинка однакова для всіх версій але в файлах є назви з версіями для desktop i mobile. 
Можливо просто назвати ці файли:
- buy-now.jpg
- buy-now-2x.jpg
- buy-now-3x.jpg

2023-04-21 15:53 UTC, Y0less commented on src/img/desktop-catalog/Cat-watch1-desktop-min.jpg
Картинки в секції catalog в  desktop і tablet варіантах однакові і мають 276 x 274 px.
Лише мобільна версія відрізняється і має 275 х 274 px. 
Думаю варто видаляти "-min" в кінці файлів після оптимізації 
![image](https://user-images.githubusercontent.com/125226395/233674122-aff0de7b-0c26-45de-a363-15a51c6204b9.png)
![image](https://user-images.githubusercontent.com/125226395/233674242-fe0b1825-b477-40e7-8406-2d1626ee20b3.png)
![image](https://user-images.githubusercontent.com/125226395/233674354-7f3dca0f-e4f0-483c-acc5-55f240c69c3a.png)

2023-04-21 15:53 UTC, Y0less commented on src/img/Hero/gif-desktop.jpg
- файли з префіксом "gif-" мабуть мають лежати в папочці "about-us"
- папочку "Hero" варто перейменувати на "hero"
- картинки для слайдера треба експортувати в форматі PNG бо там годинники з прозорим фоном. Ці картинки мають оливковий бекграунд який просвічується

2023-04-21 15:53 UTC, Y0less commented on src/img/slider/watch1-desktop-min.jpg
- експортувати в PNG

2023-04-21 17:02 UTC, ValentynaJasochka commented on src/img/slider/watch1-desktop-min.jpg
Все наче виправила

2023-04-22 09:50 UTC, ValentynaJasochka commented on src/img/slider/watch1-desktop-min.jpg
фото для catalog mobile і desktop викачала нові, tablet видалилаю Нові зображення для slider в PNG дві папки, оптимізувала. Оптимізувала about us, бо була неоптимізована

2023-04-22 11:22 UTC, Y0less approved these changes
all updated and fine

2023-04-22 11:22 UTC, merged